language: julia

os:
  - linux
  - windows
  - osx

julia:
  - 1
  - nightly

jobs:
  allow_failures:
  - julia: nightly

notifications:
  email: false

script:
    julia --project="" -e 'using Pkg; Pkg.develop(PackageSpec(path=".")); Pkg.build("MKL"; verbose=true); Pkg.test("MKL")'

