steps:
  - group: ":julia: Julia v1.8"
    steps:
      - label: ":linux: :julia: Julia v1.8 Linux x86_64"
        agents:
          os: "linux"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
          - JuliaCI/julia-test#v1: ~

      - label: ":linux: :julia: Julia v1.8 Linux i686"
        agents:
          os: "linux"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: 1
          # Use Sandbox to run inside of a 32-bit compatible rootfs
          - staticfloat/sandbox#v1:
              rootfs_url: "https://github.com/JuliaCI/rootfs-images/releases/download/v5.5/agent_linux.i686.tar.gz"
              rootfs_treehash: "9335532ac5eb036ebbb0d5b7fa1df0968f8f0f2d"
          - JuliaCI/julia#v1:
              version: 1.8
              arch: i686
          - JuliaCI/julia-test#v1: ~

      - label: ":macos: :julia: Julia v1.8 macOS x86_64"
        agents:
          os: "macos"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
          - JuliaCI/julia-test#v1: ~

      - label: ":windows: :julia: Julia v1.8 Windows x86_64"
        agents:
          os: "windows"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
          - JuliaCI/julia-test#v1: ~

      - label: ":windows: :julia: Julia v1.8 Windows i686"
        agents:
          os: "windows"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
              arch: i686
          - JuliaCI/julia-test#v1: ~

  - group: ":julia: Julia nightly"
    steps:
      - label: ":linux: :julia: Julia nightly Linux x86_64"
        agents:
          os: "linux"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: nightly
          - JuliaCI/julia-test#v1: ~

      - label: ":linux: :julia: Julia nightly Linux i686"
        agents:
          os: "linux"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: 1
          # Use Sandbox to run inside of a 32-bit compatible rootfs
          - staticfloat/sandbox#v1:
              rootfs_url: "https://github.com/JuliaCI/rootfs-images/releases/download/v5.5/agent_linux.i686.tar.gz"
              rootfs_treehash: "9335532ac5eb036ebbb0d5b7fa1df0968f8f0f2d"
          - JuliaCI/julia#v1:
              version: nightly
              arch: i686
          - JuliaCI/julia-test#v1: ~

      - label: ":macos: :julia: Julia nightly macOS x86_64"
        agents:
          os: "macos"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: nightly
          - JuliaCI/julia-test#v1: ~

      - label: ":windows: :julia: Julia nightly Windows x86_64"
        agents:
          os: "windows"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: nightly
          - JuliaCI/julia-test#v1: ~

      - label: ":windows: :julia: Julia nightly Windows i686"
        agents:
          os: "windows"
          arch: "x86_64"
        plugins:
          - JuliaCI/julia#v1:
              version: nightly
              arch: i686
          - JuliaCI/julia-test#v1: ~
